name: Test and coverage

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          stable: false
          go-version: '1.16'

      - uses: autero1/action-gotestsum@v1.0.0
        with:
          gotestsum_version: 1.7.0

      - name: Interact with gotestsum
        run: make test

# jobs:
#   build:
#     env:
#       GOPATH: ${{ github.workspace }}
#       GO111MODULE: off
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/setup-go@v2
#         with:
#           go-version: '1.16'

#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 2

#       - uses: actions/cache@v2
#         with:
#           path: ~/go/pkg/mod
#           key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#           restore-keys: |
#             ${{ runner.os }}-go-


#       - name: Run tests
#         run: make test

      # - name: Convert to Junit format
      #   run: go test -v 2>&1 | go-junit-report > report.xml
      
      # - name: Publish Unit Test Results
      #   uses: EnricoMi/publish-unit-test-result-action@v1
      #   if: always()
      #   with:
      #     files: ./**/*.xml