name: Test and coverage

on: [pull_request]

jobs:
  build:
    name: Example gotestsum interaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup gotestsum
        uses: autero1/action-gotestsum@v0.1.0
        with:
          gotestsum_version: 0.4.1
      
      - name: Interact with gotestsum
        run: gotestsum --format short-verbose