name: Test and coverage

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          stable: false
          go-version: '1.16'

      - uses: autero1/action-gotestsum@v1.0.0
        with:
          gotestsum_version: 1.7.0

    -   run: echo "GITHUB_SHA_LATEST=$(/usr/bin/git log -1 --format='%H')" >> $GITHUB_ENV

      - name: Interact with gotestsum
        run: make test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: |
            *-tests.xml
          comment_mode: create new
          deduplicate_classes_by_file_name: true
          report_individual_runs: true
          check_run_annotations: all tests
          commit: ${{env.GITHUB_SHA_LATEST}}
