name: Test and coverage

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          stable: false
          go-version: '1.16'

      - uses: autero1/action-gotestsum@v1.0.0
        with:
          gotestsum_version: 1.7.0

      - name: Interact with gotestsum
        run: make test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: |
            *-tests.xml
          comment_mode: create new
          deduplicate_classes_by_file_name: true
          report_individual_runs: true
          check_run_annotations: all tests, skipped tests

      - name: publish code cov
        uses: actions/upload-artifact@v2
        with:
          name: code covarege report
          path: coverage.out

      - name: Publish cod cov badge
        run: |
          set -x
          total=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
          if (( $(echo "$total <= 50" | bc -l) )) ; then
            COLOR=red
          elif (( $(echo "$total > 80" | bc -l) )); then
            COLOR=green
          else
            COLOR=orange
          fi
          curl "https://img.shields.io/badge/coavrege-$total%25-$COLOR" > badge.svg
          gsutil  -h "Cache-Control: no-cache" cp badge.svg gs://${SOME_BUCKET}/${PROJECT_NAME}/codcov.svg
          gsutil acl ch -u AllUsers:R gs://${SOME_BUCKET}/${PROJECT_NAME}/codcov.svg
